# Generated by Django 4.2.16 on 2024-11-11 07:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0011_carrito_carritoproducto_carrito_productos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id_categoria', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_categoria', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Regiones',
            fields=[
                ('id_region', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_region', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usuario', models.CharField(max_length=100)),
                ('gmail_usuario', models.EmailField(max_length=50)),
                ('contraseña_usuario', models.CharField(max_length=500)),
            ],
        ),
        migrations.RemoveField(
            model_name='producto',
            name='id_categoria_producto',
        ),
        migrations.AlterField(
            model_name='carrito',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id_venta', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_venta', models.DateTimeField(auto_now_add=True)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='ElementoCarrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.carrito')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.producto')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleVentas',
            fields=[
                ('id_detalle_venta', models.IntegerField(primary_key=True, serialize=False)),
                ('cantidad_producto', models.IntegerField()),
                ('precio_producto', models.IntegerField()),
                ('subtotal', models.IntegerField()),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.producto')),
                ('id_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.ventas')),
            ],
        ),
        migrations.CreateModel(
            name='Comunas',
            fields=[
                ('id_comuna', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_comuna', models.CharField(max_length=20)),
                ('id_region', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='store.regiones')),
            ],
        ),
        migrations.CreateModel(
            name='Almacenes',
            fields=[
                ('id_almacen', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_almacen', models.CharField(max_length=50)),
                ('direccion_almacen', models.TextField(max_length=100)),
                ('id_comuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.comunas')),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='id_almacen',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.almacenes'),
        ),
        migrations.AddField(
            model_name='producto',
            name='id_categoria',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='store.categorias'),
        ),
    ]
