# Generated by Django 4.2.16 on 2024-10-14 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_carrito_carritoproducto_carrito_productos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_categoria', models.CharField(max_length=50)),
            ],
        ),
    ]
