# Generated by Django 4.2.16 on 2024-12-13 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_categorias_regiones_usuario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ventas',
            name='id_usuario',
        ),
        migrations.AddField(
            model_name='categorias',
            name='imagen_categoria',
            field=models.ImageField(blank=True, null=True, upload_to='categoria/'),
        ),
        migrations.AddField(
            model_name='ventas',
            name='total_venta',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='detalleventas',
            name='id_detalle_venta',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='id_venta',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
