# Generated by Django 4.2.16 on 2024-11-05 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_elementocarrito'),
    ]

    operations = [
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usuario', models.CharField(max_length=100)),
                ('gmail_usuario', models.EmailField(default='valorDefecto', max_length=50)),
                ('contraseña_usuario', models.CharField(default='defecto', max_length=500)),
            ],
        ),
    ]
