# Generated by Django 4.2.16 on 2024-11-07 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Regiones',
            fields=[
                ('id_region', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_region', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='usuario',
            name='contraseña_usuario',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='gmail_usuario',
            field=models.EmailField(default='', max_length=50),
        ),
        migrations.CreateModel(
            name='Comunas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_comuna', models.IntegerField()),
                ('nombre_comuna', models.CharField(max_length=20)),
                ('id_region', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='store.regiones')),
            ],
        ),
        migrations.CreateModel(
            name='Almacenes',
            fields=[
                ('id_almacen', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_almacen', models.CharField(max_length=50)),
                ('direccion_almacen', models.TextField(max_length=100)),
                ('id_comuna', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='store.comunas')),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='id_almacen',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.almacenes'),
        ),
    ]
