# Generated by Django 4.2.16 on 2024-10-08 01:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='cantidad_producto',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='creacion_producto',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 10, 8, 1, 6, 20, 222344, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
