# Generated by Django 4.2.16 on 2024-10-08 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_producto_cantidad_producto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='cantidad_producto',
            field=models.IntegerField(default=0),
        ),
    ]
