# Generated by Django 4.2.16 on 2024-10-08 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_producto_cantidad_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen_producto',
            field=models.ImageField(default=0, upload_to='productos/'),
            preserve_default=False,
        ),
    ]
